#!/usr/bin/env python3
"""
Check URL mappings for all companies to ensure routing works correctly.
This script compares the URL format generated by the index template with actual filenames.
"""

import json
import os
from pathlib import Path

def normalize_url_name(company_name):
    """Simulate the URL normalization done in the index template"""
    return company_name.lower().replace(' ', '').replace('-', '').replace('_', '').replace('.', '').replace(',', '')

def get_filename_from_company_name(company_name):
    """Convert company name to expected filename format"""
    return company_name.lower().replace(' ', '_').replace('-', '_').replace('.', '').replace(',', '')

def main():
    analysis_dir = Path("analysis")
    
    # Get all comprehensive analysis files
    analysis_files = list(analysis_dir.glob('*_comprehensive_analysis.json'))
    
    print("=== URL MAPPING CHECK ===\n")
    
    # Load company names from analysis files
    companies_data = []
    
    for file_path in analysis_files:
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
                company_name = data.get('company_name', '')
                if company_name:
                    companies_data.append({
                        'company_name': company_name,
                        'filename': file_path.name,
                        'file_stem': file_path.stem.replace('_comprehensive_analysis', '')
                    })
        except Exception as e:
            print(f"Error reading {file_path}: {e}")
    
    # Sort by company name
    companies_data.sort(key=lambda x: x['company_name'])
    
    missing_mappings = []
    
    print("Company Name -> URL -> Expected Filename -> Actual Filename -> Status")
    print("-" * 80)
    
    for company in companies_data:
        company_name = company['company_name']
        url_name = normalize_url_name(company_name)
        expected_filename = f"{get_filename_from_company_name(company_name)}_comprehensive_analysis.json"
        actual_filename = company['filename']
        
        # Check if URL name would find the correct file
        # The routing looks for files like: {url_name}_comprehensive_analysis.json
        expected_by_routing = f"{url_name}_comprehensive_analysis.json"

        if expected_by_routing == actual_filename:
            status = "✅ OK"
        else:
            status = "❌ NEEDS MAPPING"
            missing_mappings.append({
                'url_name': url_name,
                'actual_filename': actual_filename
            })
        
        print(f"{company_name:<25} -> {url_name:<20} -> {expected_filename:<35} -> {actual_filename:<35} -> {status}")
    
    print(f"\n=== SUMMARY ===")
    print(f"Total companies: {len(companies_data)}")
    print(f"Need special mappings: {len(missing_mappings)}")
    
    if missing_mappings:
        print(f"\n=== REQUIRED SPECIAL CASE MAPPINGS ===")
        for mapping in missing_mappings:
            print(f'        "{mapping["url_name"]}": "{mapping["actual_filename"]}",')

if __name__ == "__main__":
    main()
